<?php

# Session start must be in all pages that write / access session variables
session_start();

include("components/interfaceSettings.php");
include("components/menu.php");

print '<HTML><HEAD>';
PrintHeader("ASPASIA: Analysis Settings");

# Javascript method to check the data entry on the form
print '<script type="text/javascript">
function checkLHC() 
{
  var samples = document.getElementById("numberparameterSamples").value;
  var meth = document.getElementById("algorithm").value;

  if (meth == "") { alert("You must select a Latin-Hypercube Sampling Algorithm"); return false; }
  else 
  { 
 	if (samples == "") { alert("You must specify the number of samples to select from the hypercube"); return false; }
	else
	{
			return true; 
	}
  } 
}

function checkeFAST() 
{
  var samples = document.getElementById("efastCurveSamples").value;
  var curves = document.getElementById("efastCurves").value;

  if (curves == "") { alert("You must specify the number of resample curves to use in sampling"); return false; }
  else 
  { 
 	if (samples == "") { alert("You must specify the number of samples to select from the hypercube"); return false; }
	else
	{
			return true; 
	}
  } 
}

function checkNewEvent() 
{
  var solver = document.getElementById("solverOutput").value;
  var interv = document.getElementById("interventionFileName").value;

  if (solver == "") { alert("You must specify the path to an SBML solver output file"); return false; }
  else 
  { 
	if (interv == "") { alert("You must specify a name for the new SBML Model File"); return false; }
	else
	{
		return true; 
	}
  } 
}
function checkLHCProvided() 
{
  var samples = document.getElementById("sampleFile").value;

  if (samples == "") { alert("You must specify the path to an LHC Sample file (CSV)"); return false; }
  else 
  { 
	return true; 
  } 
}
</script></head>';



#### Now set up the HTML Page


if($_SESSION['experimentType']=="LHC")
{
	print '<br>
	<div id="textheading">ASPASIA Analysis Settings</div>
	<br>
	<div id="formtable">
	<table width="85%"  border="0" cellspacing="0" cellpadding="0">
	<TR><TD>Here you state settings for the Sensitivity Analysis technique that you have chosen. These will differ dependent on the 	technique<br><br>
	For a more detailed description of what is required, hover your mouse over the data entry box</TD></TR></TABLE>
	</div>
	<BR>

	<form name="AnalysisSpecificParams" action="Analysis_Specific_Parameters_Process.php" method="post" onsubmit="return checkLHC()">
		<table cellpadding=5>
		<TR title="Enter the number of parameter sets that should be generated by the hypercube. In typical YCIL studies, we use between 200 and 500 sample sets">
			<TD>Number of Parameter Samples to Generate:</TD><TD><input type="text" size="5" name="numberparameterSamples" id="numberparameterSamples"></TD>
		</TR>
		<TR title="Select the algorithm to use to sample the parameter space. Normal is ok, and selects a good sample set that covers the parameter space. An optimal sample cuts out any correlations between the sets, but takes a very long time to run">
			<TD>Sampling Algorithm: </TD><TD> <select name="algorithm" id="algorithm" SIZE=2>
				<option value="normal">Normal</option>
				<option value="optimal">Optimal (Very Long Process)</option>
			</select></TD>
		</TR></TABLE><HR>
		<input type="submit" value="Next: Aspasia Settings File" ></form>';

	}
	else if($_SESSION['experimentType']=="eFAST")
	{
		print '<br>
		<div id="textheading">ASPASIA Analysis Settings</div>
		<br>
		<div id="formtable">
		<table width="85%"  border="0" cellspacing="0" cellpadding="0">
		<TR><TD>Here you state settings for the Sensitivity Analysis technique that you have chosen. These will differ dependent on 			the technique<br><br>
		For a more detailed description of what is required, hover your mouse over the data entry box</TD></TR></TABLE>
		</div>
		<BR>

		<form name="AnalysisSpecificParams" action="Analysis_Specific_Parameters_Process.php" method="post" onsubmit="return checkeFAST()">
		<table cellpadding=5>
		<TR title="To mitigate the selection of identical parameter sets, eFAST employs a phase shift, which shifts the frequency of the curve from which the parameter samples are generated. Read the documentation in the Worked Example for more information on calculating this number. YCIL studies tend to use 3 curves">
				<TD>Number of Resampling Curves to Use</TD><TD><input type="text" size="5" id="efastCurves" name="efastCurves"></TD>
		</TR>
		<TR title="Enter the number of parameter sets that should be generated from the sample curve. Again read the documentation of the technique to set this number. In typical YCIL studies, we use 65">
			<TD>Number of Parameter Samples to Generate Per Curve</TD><TD><input type="text" size="5" id="efastCurveSamples" name="efastCurveSamples"></TD>
		</TR></TABLE><HR>
		<input type="submit" value="Next: Aspasia Settings File" ></form>';

	}
	else if($_SESSION['experimentType']=="NewEvent")
	{
		print '<br><div id="textheading">Simulate an Intervention: The Steady State File</div><br>

		<div id="formtable">
		<table width="85%"  border="0" cellspacing="0" cellpadding="0">
		<TR><TD>Using this technique, you can introduce an intervention once an SBML Model has reached a steady state<br><br>
		To do this, you need to provide a SBML Solver output file where your model has reached a steady state. Provide the full path to this file below
		<br>Additionally, enter a filename to give to the new SBML model containing the intervention. No path required, this will be placed in the directory given in the previous screen.
<br><br></TD></TR></TABLE>
		</div>
		<BR>

		<form name="AnalysisSpecificParams" action="Analysis_Specific_Parameters_Process.php" method="post" onsubmit="return checkNewEvent()">
		<table cellpadding=5>
		<TR title="Full path to the location on your hard disk where the output from the SBML solver can be found. This file will be used to initialise a new SBML Model file.">
			<TD>SBML Solver Output File Path</TD><TD><input type="text" size="52" id="solverOutput" name="solverOutput"></TD>
		</TR>
		<TR title="File name (not full path) to give the generated SBML model containing the intervention.">
			<TD>New SBML Model File Name</TD><TD><input type="text" size="32" id="interventionFileName" name="interventionFileName"></TD>
		</TR>
		
		</TABLE><HR>
		<input type="submit" value="Next: Aspasia Settings File" ></form>';

	}
	if($_SESSION['experimentType']=="LHC_Provided")
	{
		print '<br>
		<div id="textheading">ASPASIA Analysis Settings: Use Pre-Generated LHC Sample</div>
		<br>
		<div id="formtable">
		<table width="85%"  border="0" cellspacing="0" cellpadding="0">
		<TR><TD>Sometimes you may want to run an altered model with the same set of parameters generated by a previous latin-hypercube experiment. You can do this here, by providing the full path to the CSV file containing all the samples This should consist of a column for each parameter being sampled, with the sample set in each row. The header should contain the parameter names.<br><br>
		Provide the full path to this file below</TD></TR></TABLE>
		</div>
		<BR>	

		<form name="AnalysisSpecificParams" action="Analysis_Specific_Parameters_Process.php" method="post" onsubmit="return checkLHCProvided()">
		<table cellpadding=5>
		<TR title="Full path to the location on your hard disk where the Latin-Hypercube CSV file can be found.">
			<TD>Path to LHC Sample File</TD><TD><input type="text" size="52" id="sampleFile" name="sampleFile"></TD>
		</TR>
		</TABLE><HR>
		<input type="submit" value="Next: Aspasia Settings File" ></form>';
	
	}


?>
